name: Run Tests and Notify Slack

on:
  workflow_dispatch:  # 手動トリガーのみ

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev  # GitHub Environmentを指定

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Notify Slack
      if: always()
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ vars.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "テスト ${{ job.status == 'success' && '成功' || '失敗' }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ job.status == 'success' && '✅' || '❌' }} テスト結果 | ${{ github.repository }} | ブランチ: ${{ github.ref_name }}"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "実行者: ${{ github.actor }} | 実行日時: ${{ github.event.repository.updated_at }}"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "詳細を見る"
                    },
                    "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ],
            "attachments": [
              {
                "color": "${{ job.status == 'success' && '#36a64f' || '#ff0000' }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": " "
                    }
                  }
                ]
              }
            ]
          }