name: Jest Tests and Notify Slack

on:
  workflow_dispatch:  # 手動トリガーのみ

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev  # GitHub Environmentを指定

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Notify Slack
      if: always()
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ vars.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "テスト ${{ job.status == 'success' && '成功' || '失敗' }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*テスト ${{ job.status == 'success' && '成功 :white_check_mark:' || '失敗 :x:' }}*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*リポジトリ:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*ブランチ:*\n${{ github.ref_name }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*実行者:*\n${{ github.actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*ステータス:*\n${{ job.status }}"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "ワークフロー詳細を見る"
                    },
                    "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }